name: Menu Service CD (DockerHub Pull & Deploy)

on:
  push:
    branches:
      - main

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 📡 SSH into EC2 & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Go to infra directory
            cd dinegrid-infra

            # Pull latest images from DockerHub
            docker-compose pull

            # Stop existing containers
            docker-compose down

            # Start fresh containers in detached mode
            docker-compose up -d

            # Clean up unused images
            docker image prune -f
